### ISSUE TITLE
MultiSelect input scrolling with tabs

### ISSUE THREAD

**Issue by erwstout** [elm-street-technology/elevate-ui#131]
When adding tabs to a MultiSelect the input can grow in width. A more desired effect would be to limit the width and then allow the tabs to wrap to the next line and be scrollable. 

![multiselectgrow](https://user-images.githubusercontent.com/9441913/48161006-b4bc2100-e296-11e8-9772-8046042264ba.gif)

**Comment by chrisheninger** [comment]
Fixed and released in `v0.22.2`
