### ISSUE TITLE
Theme Permanently Overwritten After First Overwrite

### ISSUE THREAD

**Issue by jwdotjs** [elm-street-technology/elevate-ui#153]
https://github.com/elm-street-technology/elevate-ui/blob/da04809feec51530e21548c95d404c083a50b7a8/src/ThemeProvider/index.js#L194

When a theme has overwrite, it's permanent thereafter. I think we can change this line to `  const mergedTheme = theme ? merge({}, defaultTheme, theme) : defaultTheme;` to prevent permanent overwrite.

**Comment by chrisheninger** [comment]
Published as `0.25.0`
