### ISSUE TITLE
Autocomplete - Additional work

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#156]
Additional work that can be completed with the merging of #155 

- [x] Add an example in the docs showing autocomplete (can fake fetch using a promise like we do on the "Feed" component #145)
- [x] Copy over logic to allow a single `Select` to also have autocomplete functionality
- [x] Also add an example for Select
- [x] Maybe add a loading indicator to show when results are being fetched?

**Comment by erwstout** [comment]
PR https://github.com/elm-street-technology/elevate-ui/pull/160

**Comment by chrisheninger** [comment]
Published as `v0.29.0` 👏
