### ISSUE TITLE
Tooltip - Additional work

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#157]
<img width="432" alt="screen shot 2018-12-03 at 9 22 00 am" src="https://user-images.githubusercontent.com/5051745/49386581-2001e300-f6dd-11e8-8438-fe435feeb5f4.png">

- [x] Tooltips should be centered horizontally (or vertically if left/right) to the element they are wrapping
- [x] Tooltips should have a little `v` `<` `etc.` caret coming out of the side to make it a little more speech bubble/tooltippy
- [x] We should add an example that is on a plain Icon element like a `<Info />` or `<InfoOutline />` icon from elevate-ui
- [x] We should add an example that is on a form scaffold label to show how it can be used to describe what a certain form input/value will do.

**Comment by erwstout** [comment]
https://github.com/elm-street-technology/elevate-ui/pull/158
