### ISSUE TITLE
Accordion - Don't Render Children If Accordion Isn't Open

### ISSUE THREAD

**Issue by jwdotjs** [elm-street-technology/elevate-ui#172]
As an engineer, I want children for the accordion to be null when the accordion isn't open (we can keep `height: 0`). The reasoning is I might want to render something like an iFrame or a container that fetches data from the backend and accordion child will trigger loading all its content even if the user never expands the accordion.

Instead we should wait for that action from the user before loading the accordion children

**Comment by chrisheninger** [comment]
Published as `v0.30.0`
