### ISSUE TITLE
Accordion Enhancements

### ISSUE THREAD

**Issue by dillonmorris91** [elm-street-technology/elevate-ui#218]
- Change default Accordion to one that has no drawers open on page-load
- Update chevron color to gray["500"]
- Include an option to "expand all" 
(ex. sidebar of Gatsby Docs sidebar https://www.gatsbyjs.org/docs/)

**Comment by erwstout** [comment]
@dillonmorris91 do you think you can get to this before the 1.0.0 release or should we add it after?

**Comment by erwstout** [comment]
~Include an option to "expand all"~
