### ISSUE TITLE
Add basic border styles to Theme

### ISSUE THREAD

**Issue by dillonmorris91** [elm-street-technology/elevate-ui#223]
We currently don't have the ability to do something like this:

```js
root: {
    borderBottom: theme.borders["default"],
}
```

I imagine the styles for that would be something like this:

```js
borders: {
   default: `1px solid ${theme.colors.gray("600")}`,
}
```

**Comment by erwstout** [comment]
https://github.com/elm-street-technology/elevate-ui/pull/225
