### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#23]
New Components
- [x] ToggleGroup
- [x] Toggle
- [x] Checkbox
- [x] Radio

Added to demo
- [x] Checkboxes
- [x] Radios

Updated dependencies
- [x] `flow-bin` 0.68.x => 0.71.x
- [x] `lodash` 4.17.5 => 4.17.10
- [x] `react-jss` 8.1.0 => 8.4.0
- [x] `react-table` 6.8.0 => 6.8.2

**Comment by maxkorp** [comment]
I'ma go ahead and close this, since it's released.
