### ISSUE TITLE
Toggle Components

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#27]
- [x] Checkbox
- [x] Radio
- [x] Toggle
- [x] ToggleGroup

I'm open to how we want to implement these– but we need to at least update them to work properly as formik `Field` components– as well as update the demo to include an example.

**Comment by maxkorp** [comment]
Settled on 
 - Toggle: Externally available, but not formik compatible without wrapper, its a building block. 
 - Checkbox: A single checkbox
 - CheckboxGroup: A series of checkboxes which add or remove values from a single array value
 - RadioGroup: A series of radios which set the value like typical radios
