### ISSUE TITLE
Deploy process for demo/gh-pages?

### ISSUE THREAD

**Issue by maxkorp** [elm-street-technology/elevate-ui#31]
What is it? Can we automate it maybe?

**Comment by chrisheninger** [comment]
`yarn run deploy` from inside the `demo` directory will build the demo (CRApp) and publish it to GitHub Pages. 👍 

I'll let you run it and close this ticket when it's updated.

**Comment by maxkorp** [comment]
Deployed for now
Gonna add a bit to the deploy script for the root of the project to also cd in to demo and deploy to gh-pages

**Comment by chrisheninger** [comment]
Deploy demo with deploy to npm = 👍 imo
