### ISSUE TITLE
MultiSelect component - entered text is not removed when making a selection

### ISSUE THREAD

**Issue by mattlorey** [elm-street-technology/elevate-ui#45]
Current behavior:

When entering text into a MultiSelect component and then selected one of the matched options with either keyboard or mouse, the entered text stays.

Expected behavior:

When a selection is made, the entered text is removed

<img width="492" alt="screen shot 2018-06-01 at 8 12 09 am" src="https://user-images.githubusercontent.com/142669/40848386-f22b2f22-6573-11e8-8eaf-20a8d5b71f0f.png">

**Comment by chrisheninger** [comment]
Fix here https://github.com/elm-street-technology/elevate-ui/commit/a6110864c376e6921b3705b3b5041fa7e15f34c5, released as v0.3.3
