### ISSUE TITLE
Typography - headings other then `<h1>`

### ISSUE THREAD

**Issue by erwstout** [elm-street-technology/elevate-ui#52]
Would it make sense to add other heading levels to the `<Typography />` component to keep a consistent style in check?

**Comment by chrisheninger** [comment]
Absolutely– would you mind adding this as a task to #51 and we'll have that entire ticket/issue be a "Typography Component Updates"?  Can then close this issue and we'll do it all in one swoop. 👍

**Comment by erwstout** [comment]
Sure thing! Added to #51
