### ISSUE TITLE
Select Dropdown Bold

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#75]
![select-bold](https://user-images.githubusercontent.com/5051745/44929812-2c0e8b00-ad11-11e8-801c-2a6b7d408ef9.gif)

Mousing over options in select is hurting my eyes– I think it has something to do with the font-weight changing and the text slightly shifting as a result. (combined with the colors getting inverse/flipped at the same time)

We should definitely at least investigate dropping the font-weight on mouseover.

**Comment by dillonmorris91** [comment]
I agree Chris, there is too much going on here. I say we change the background color to a light grey on hover instead of Teal. This way we can keep the font color black and not have to change any font-weights.

**Comment by chrisheninger** [comment]
I snuck this in with the updates to elevate-ui.com, I think in v0.13.4 or 0.13.5 🙂

https://elevate-ui.com/multi-select
