### ISSUE TITLE
Color Updates

### ISSUE THREAD

**Issue by dillonmorris91** [elm-street-technology/elevate-ui#86]
<img width="500" alt="screen shot 2018-09-13 at 2 14 34 pm" src="https://user-images.githubusercontent.com/27472341/45516266-68090d80-b75f-11e8-9950-fd3229c80754.png">

**Comment by chrisheninger** [comment]
I think we're shipping color.js with the button component.

If we're including it in our bundles, we might as well take advantage of it's functions.

If we can drop it, we could probably save some kilobytes by using something like https://glitch.com/edit/#!/color-gradient?path=script.js:1:0

**Comment by erwstout** [comment]
I'd love to get this out the door, any updates on this?

**Comment by erwstout** [comment]
https://github.com/elm-street-technology/elevate-ui/pull/199
